Installing dependencies from lock file

Package operations: 17 installs, 0 updates, 0 removals

  • Installing frozenlist (1.8.0)
  • Installing idna (3.11)
  • Installing multidict (6.7.1)
  • Installing propcache (0.4.1)
  • Installing typing-extensions (4.15.0)

  DBusException

  org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.kwalletd5': no such name

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  DBusException

  org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  InitError

  Failed to open keyring: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6.

  at /usr/lib/python3/dist-packages/keyring/backends/kwallet.py:100 in connected
       96│             remote_obj = bus.get_object(self.bus_name, self.object_path)
       97│             self.iface = dbus.Interface(remote_obj, 'org.kde.KWallet')
       98│             self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)
       99│         except dbus.DBusException as e:
    → 100│             raise InitError('Failed to open keyring: %s.' % e)
      101│ 
      102│         if self.handle < 0:
      103│             return False
      104│         self._migrate(service)


  DBusException

  org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.kwalletd5': no such name

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  DBusException

  org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  InitError

  Failed to open keyring: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6.

  at /usr/lib/python3/dist-packages/keyring/backends/kwallet.py:100 in connected
       96│             remote_obj = bus.get_object(self.bus_name, self.object_path)
       97│             self.iface = dbus.Interface(remote_obj, 'org.kde.KWallet')
       98│             self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)
       99│         except dbus.DBusException as e:
    → 100│             raise InitError('Failed to open keyring: %s.' % e)
      101│ 
      102│         if self.handle < 0:
      103│             return False
      104│         self._migrate(service)


  DBusException

  org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.kwalletd5': no such name

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  DBusException

  org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  InitError

  Failed to open keyring: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6.

  at /usr/lib/python3/dist-packages/keyring/backends/kwallet.py:100 in connected
       96│             remote_obj = bus.get_object(self.bus_name, self.object_path)
       97│             self.iface = dbus.Interface(remote_obj, 'org.kde.KWallet')
       98│             self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)
       99│         except dbus.DBusException as e:
    → 100│             raise InitError('Failed to open keyring: %s.' % e)
      101│ 
      102│         if self.handle < 0:
      103│             return False
      104│         self._migrate(service)


  DBusException

  org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.kwalletd5': no such name

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  DBusException

  org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  InitError

  Failed to open keyring: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6.

  at /usr/lib/python3/dist-packages/keyring/backends/kwallet.py:100 in connected
       96│             remote_obj = bus.get_object(self.bus_name, self.object_path)
       97│             self.iface = dbus.Interface(remote_obj, 'org.kde.KWallet')
       98│             self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)
       99│         except dbus.DBusException as e:
    → 100│             raise InitError('Failed to open keyring: %s.' % e)
      101│ 
      102│         if self.handle < 0:
      103│             return False
      104│         self._migrate(service)


  DBusException

  org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.kwalletd5': no such name

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  DBusException

  org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6

  at /usr/lib/python3/dist-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│ 
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  InitError

  Failed to open keyring: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6.

  at /usr/lib/python3/dist-packages/keyring/backends/kwallet.py:100 in connected
       96│             remote_obj = bus.get_object(self.bus_name, self.object_path)
       97│             self.iface = dbus.Interface(remote_obj, 'org.kde.KWallet')
       98│             self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)
       99│         except dbus.DBusException as e:
    → 100│             raise InitError('Failed to open keyring: %s.' % e)
      101│ 
      102│         if self.handle < 0:
      103│             return False
      104│         self._migrate(service)

